In [3]:
import pandas as pd
import mteb
from sentence_transformers import SentenceTransformer

# Select model
model_name = "sentence-transformers/all-MiniLM-L6-v2"
# model_name = "intfloat/multilingual-e5-large" # Trop lourd
# model_name = "BAAI/bge-m3"
model_name = "BAAI/bge-small-en-v1.5"
# model_name = "Cohere/Cohere-embed-multilingual-light-v3.0"
# model_name = "Qwen/Qwen3-Embedding-0.6B"
# model_name = "Qwen/Qwen3-Embedding-4B"
# model_name = "google/gemini-embedding-001"
# model_name = "openai/text-embedding-ada-002"
# model = SentenceTransformer("dangvantuan/sentence-camembert-large")

model = mteb.get_model(model_name) # if the model is not implemented in MTEB it will be eq. to SentenceTransformer(model_name)

# local_models = {
#     'all-mpnet-base-v2': SentenceTransformer('all-mpnet-base-v2'),
#     'all-MiniLM-L6-v2': SentenceTransformer('all-MiniLM-L6-v2'),
#     'e5-base': SentenceTransformer('intfloat/e5-base-v2')
# }

# Select tasks
# tasks = mteb.get_tasks(tasks=["Banking77Classification.v2"])
tasks = mteb.get_tasks(tasks=[
    # 'STS12',
    # 'STS13',
    # 'STS14',
    # 'STS15',
    # 'STS16',
    # 'STS22.v2',
    'STSBenchmark', 
    # 'SICK-R',
    ])

# evaluate
results = mteb.evaluate(model, tasks=tasks)

Model prompts specified, these will overwrite the default model prompts. Current prompts will be:
 {'query': 'Represent this sentence for searching relevant passages: '}
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\models\sentence_transformer_wrapper.py:87: UserWarning: Model prompts specified, these will overwrite the default model prompts. Current prompts will be:
 {'query': 'Represent this sentence for searching relevant passages: '}
  warnings.warn(msg)
SentenceTransformers that use prompts most often need to be configured with at least 'query' and 'document' prompts to ensure optimal performance. Received {'query': 'Represent this sentence for searching relevant passages: '}
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\models\sentence_transformer_wrapper.py:110: UserWarning: SentenceTransformers that use prompts most often need to be configured with at least 'query' and 'document' prompts to ensure optimal performance. Received {'query': 'Represent this sentence for searching relevant passages: '}
  warnings.warn(msg)
Evaluating task STSBenchmark: 100%|██████████| 1/1 [00:00<00:00, 90.84it/s]

In [4]:
df_ = results.to_dataframe(format="long")
df_

c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\results\model_result.py:68: FutureWarning: The provided callable <function mean at 0x000002397035C2C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  .agg(score=("score", aggregation_fn))

               model_name     task_name    score
0  BAAI/bge-small-en-v1.5  STSBenchmark  0.85863

In [17]:
results.task_results[0].scores

{'test': [{'pearson': 0.843129,
   'spearman': 0.85863,
   'cosine_pearson': 0.843129,
   'cosine_spearman': 0.85863,
   'manhattan_pearson': 0.851387,
   'manhattan_spearman': 0.856401,
   'euclidean_pearson': 0.853616,
   'euclidean_spearman': 0.85863,
   'main_score': 0.85863,
   'hf_subset': 'default',
   'languages': ['eng-Latn']}]}

In [ ]:
import pandas as pd
import mteb
from sentence_transformers import SentenceTransformer

df_ = pd.DataFrame()

for model_name in [
    # "sentence-transformers/all-MiniLM-L6-v2",
    # "intfloat/multilingual-e5-large", # Trop lourd
    # "BAAI/bge-m3", # Trop lourd
    # "BAAI/bge-small-en-v1.5",
    # "Cohere/Cohere-embed-multilingual-light-v3.0",
    # "Qwen/Qwen3-Embedding-0.6B",
    # "Qwen/Qwen3-Embedding-4B", # Trop lourd
    # "google/gemini-embedding-001", # Ne fonctionne pas
    "openai/text-embedding-ada-002" # Ne fonctionne pas
    ]:
    
    model = mteb.get_model(model_name)

    tasks = mteb.get_tasks(tasks=[
        'STS12', 
        'STS13', 
        'STS14',
        'STS15',
        'STS16',
        'STSBenchmark', 
        'SICK-R'
        ])

    # evaluate
    results = mteb.evaluate(model, tasks=tasks)

    df_ = pd.concat([df, results.to_dataframe(format="long")])

df_

## Test DataFrame

In [81]:
df

                                    model_name     task_name     score
0       sentence-transformers/all-MiniLM-L6-v2        SICK-R  0.775824
1       sentence-transformers/all-MiniLM-L6-v2         STS12  0.723690
2       sentence-transformers/all-MiniLM-L6-v2         STS13  0.806032
3       sentence-transformers/all-MiniLM-L6-v2         STS14  0.755891
4       sentence-transformers/all-MiniLM-L6-v2         STS15  0.853896
5       sentence-transformers/all-MiniLM-L6-v2         STS16  0.789895
6       sentence-transformers/all-MiniLM-L6-v2  STSBenchmark  0.820325
0                       BAAI/bge-small-en-v1.5        SICK-R  0.794099
1                       BAAI/bge-small-en-v1.5         STS12  0.774434
2                       BAAI/bge-small-en-v1.5         STS13  0.829800
3                       BAAI/bge-small-en-v1.5         STS14  0.818354
4                       BAAI/bge-small-en-v1.5         STS15  0.872654
5                       BAAI/bge-small-en-v1.5         STS16  0.849340
6                       BAAI/bge-small-en-v1.5  STSBenchmark  0.858630
0  Cohere/Cohere-embed-multilingual-light-v3.0        SICK-R  0.777348
1  Cohere/Cohere-embed-multilingual-light-v3.0         STS12  0.756016
2  Cohere/Cohere-embed-multilingual-light-v3.0         STS13  0.762409
3  Cohere/Cohere-embed-multilingual-light-v3.0         STS14  0.773960
4  Cohere/Cohere-embed-multilingual-light-v3.0         STS15  0.861588
5  Cohere/Cohere-embed-multilingual-light-v3.0         STS16  0.839054
6  Cohere/Cohere-embed-multilingual-light-v3.0  STSBenchmark  0.834210
0                    Qwen/Qwen3-Embedding-0.6B        SICK-R  0.848571
1                    Qwen/Qwen3-Embedding-0.6B         STS12  0.833912
2                    Qwen/Qwen3-Embedding-0.6B         STS13  0.915034
3                    Qwen/Qwen3-Embedding-0.6B         STS14  0.868411
4                    Qwen/Qwen3-Embedding-0.6B         STS15  0.913529
5                    Qwen/Qwen3-Embedding-0.6B         STS16  0.903521
6                    Qwen/Qwen3-Embedding-0.6B  STSBenchmark  0.912247

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("dangvantuan/sentence-camembert-large")

sentences = [
    "C'est une personne heureuse",
    "C'est un chien heureux",
    "C'est une personne très heureuse",
    "Aujourd'hui est une journée ensoleillée"
]
embeddings = model.encode(sentences)

similarities = model.similarity(embeddings, embeddings)
print(similarities.shape)
# [4, 4]

In [ ]:
import mteb

# Modele
model = mteb.get_model("BAAI/bge-small-en-v1.5") 
# Tache
tasks = mteb.get_tasks(tasks=['STSBenchmark'])
# evaluate
results = mteb.evaluate(model, tasks=tasks)
results.to_dataframe(format="long")

c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\models\sentence_transformer_wrapper.py:87: UserWarning: Model prompts specified, these will overwrite the default model prompts. Current prompts will be:
 {'query': 'Represent this sentence for searching relevant passages: '}
  warnings.warn(msg)
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\models\sentence_transformer_wrapper.py:110: UserWarning: SentenceTransformers that use prompts most often need to be configured with at least 'query' and 'document' prompts to ensure optimal performance. Received {'query': 'Represent this sentence for searching relevant passages: '}
  warnings.warn(msg)
Evaluating task STSBenchmark: 100%|██████████| 1/1 [00:00<00:00, 57.01it/s]

In [14]:
df_ = results.to_dataframe(format="long")
df_

c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\results\model_result.py:68: FutureWarning: The provided callable <function mean at 0x0000023C77D1F6A0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  .agg(score=("score", aggregation_fn))

               model_name     task_name    score
0  BAAI/bge-small-en-v1.5  STSBenchmark  0.85863

In [30]:
df = pd.DataFrame([[11, 1, 0], [12, 1, 0], [13, 3, 0], [14, 7, 0],
                   [15, 10, 0], [16, 12, 1], [17, 15, 10], [18, 60, 40],
                   [19, 90, 120], [20, 120, 200], [21, 140, 290], [22, 170, 320],
                   [23, 200, 350], [24, 240, 400], [25, 270, 450]], columns=['A', 'F', 'M'])
df

     A    F    M
0   11    1    0
1   12    1    0
2   13    3    0
3   14    7    0
4   15   10    0
5   16   12    1
6   17   15   10
7   18   60   40
8   19   90  120
9   20  120  200
10  21  140  290
11  22  170  320
12  23  200  350
13  24  240  400
14  25  270  450

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

sentences = [
    "Bonjour, ceci est un simple texte de vectorisation",
]
embeddings = model.encode(sentences)
print(embeddings.shape)

(1, 384)

In [17]:
import pandas as pd
import mteb

df = pd.DataFrame()

for model_name in [ "sentence-transformers/all-MiniLM-L6-v2",
                    "Qwen/Qwen3-Embedding-0.6B",
                    "Cohere/Cohere-embed-multilingual-light-v3.0",
                    "BAAI/bge-small-en-v1.5"]:
    print(model_name, '-' * 80)
    model = mteb.get_model(model_name)
    tasks = mteb.get_tasks(tasks=['STSBenchmark'])
    results = mteb.evaluate(model, tasks=tasks)
    df_temp = results.to_dataframe(format="long")
    df = pd.concat([df, df_temp], ignore_index=True)
df

sentence-transformers/all-MiniLM-L6-v2 --------------------------------------------------------------------------------

Evaluating task STSBenchmark: 100%|██████████| 1/1 [00:00<00:00, 313.17it/s]
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\results\model_result.py:68: FutureWarning: The provided callable <function mean at 0x000002397035C2C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  .agg(score=("score", aggregation_fn))

Qwen/Qwen3-Embedding-0.6B --------------------------------------------------------------------------------

Evaluating task STSBenchmark: 100%|██████████| 1/1 [00:00<00:00, 366.51it/s]
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\results\model_result.py:68: FutureWarning: The provided callable <function mean at 0x000002397035C2C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  .agg(score=("score", aggregation_fn))

Cohere/Cohere-embed-multilingual-light-v3.0 --------------------------------------------------------------------------------

Evaluating task STSBenchmark: 100%|██████████| 1/1 [00:00<00:00, 76.93it/s]
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\results\model_result.py:68: FutureWarning: The provided callable <function mean at 0x000002397035C2C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  .agg(score=("score", aggregation_fn))

BAAI/bge-small-en-v1.5 --------------------------------------------------------------------------------

Model prompts specified, these will overwrite the default model prompts. Current prompts will be:
 {'query': 'Represent this sentence for searching relevant passages: '}
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\models\sentence_transformer_wrapper.py:87: UserWarning: Model prompts specified, these will overwrite the default model prompts. Current prompts will be:
 {'query': 'Represent this sentence for searching relevant passages: '}
  warnings.warn(msg)
SentenceTransformers that use prompts most often need to be configured with at least 'query' and 'document' prompts to ensure optimal performance. Received {'query': 'Represent this sentence for searching relevant passages: '}
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\models\sentence_transformer_wrapper.py:110: UserWarning: SentenceTransformers that use prompts most often need to be configured with at least 'query' and 'document' prompts to ensure optimal performance. Received {'query': 'Represent this sentence for searching relevant passages: '}
  warnings.warn(msg)
Evaluating task STSBenchmark: 100%|██████████| 1/1 [00:00<00:00, 166.70it/s]
c:\Users\Utilisateur\Documents\Veille_Technique\env_veille_tech\Lib\site-packages\mteb\results\model_result.py:68: FutureWarning: The provided callable <function mean at 0x000002397035C2C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  .agg(score=("score", aggregation_fn))

                                    model_name     task_name     score
0       sentence-transformers/all-MiniLM-L6-v2  STSBenchmark  0.820325
1                    Qwen/Qwen3-Embedding-0.6B  STSBenchmark  0.912247
2  Cohere/Cohere-embed-multilingual-light-v3.0  STSBenchmark  0.834210
3                       BAAI/bge-small-en-v1.5  STSBenchmark  0.858630